"""Initial migration

Revision ID: f0d866a1fb91
Revises: 
Create Date: 2026-02-25 04:12:03.010738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d866a1fb91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.String(length=20), nullable=True))
        batch_op.alter_column('total_interest',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.alter_column('total_interest',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
